### ISSUE TITLE
[Question] Would it possible to clone only specific "directory" from GitHub repository

### ISSUE THREAD

**Issue by swapnil-kotwal-sp** [alexvasilkov/GradleVcsDependencyPlugin#11]
Hey,

1. I'm just curious that some time whole GitHub repo doesn't required to be cloned, (pulled) , is it possible to pull specific `dir` from GitHub repo?

**Comment by alexvasilkov** [comment]
1. No, you cannot clone single directory with git. But you can use `projectPath` parameter to specify which folder you would like to add as dependency.
