### ISSUE TITLE
keepUpdated not honored

### ISSUE THREAD

**Issue by bonivi** [alexvasilkov/GradleVcsDependencyPlugin#12]
in `settings.gradle` I have something like:

```
git {
    fetch 'https://example.com/repository.git', {
        dir "$rootDir/gradle/scripts"
        keepUpdated false
    }
}
```
but every time when I invoke **gradle build -i** I see the messages like "Git updating to version 'master' for ..."

**Comment by alexvasilkov** [comment]
Thanks for reporting the issue, it is fixed now and released in v2.0.2
