### ISSUE TITLE
[Question]: 'Invalid remote: origin' error when starting the build

### ISSUE THREAD

**Issue by stalexmr** [alexvasilkov/GradleVcsDependencyPlugin#13]
The part of my settings.gradle:
```
plugins {
    id 'com.alexvasilkov.git-dependencies' version '2.0.1'
}
```
The part of my build.gradle:
```
git {
    implementation 'git@gitlab.int.com:QA/order.git'
}
```

When I start the build, I see the following messages in the terminal:
```
 ./gradlew build
Git dependency: Added 'order' for 'project'
Git clone started 'git@gitlab.int.com:QA/order.git' at version 'master'

FAILURE: Build failed with an exception.

* What went wrong:
Failed to notify build listener.
> Invalid remote: origin
```

If I try to test connection:
` ssh -T git@gitlab.int.com`
Everything works fine

If I try to clone:
`git clone git@gitlab.int.com:QA/order.git`
Everything works fine

I realize that probably the problem lays outside your plugin, but maybe you may help me with this issue?

**Comment by alexvasilkov** [comment]
Hmm, I don't really know what can be a poblem here. I checked that ssh fetching works fine for my repos (hosted with Bitbucket).

Please try to delete the repo's local directory and run `./gradlew --stacktrace` what is the full stacktrace?

**Comment by stalexmr** [comment]
Sorry for late answer. I run with `./gradlew --stacktrace` ang get
```
Caused by: org.eclipse.jgit.api.errors.InvalidRemoteException: Invalid remote: origin
Caused by: org.eclipse.jgit.errors.NoRemoteRepositoryException: git@gitlab.int.com:QA/ag-task.git: git@gitlab.int.com: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,keyboard-interactive).
```
Then just simple added my ssh private key:
`ssh-add ~/.ssh/id_rsa   `

And everything run fine.

Thank your for assistan and sorry for that noice

**Comment by alexvasilkov** [comment]
Aha, strange that `ssh -T git@gitlab.int.com` worked fine then. Anyway, I'm glad that it works for you now, will close the issue.
