### ISSUE TITLE
Unable to suppress plugin output using --quiet option

### ISSUE THREAD

**Issue by bonivi** [alexvasilkov/GradleVcsDependencyPlugin#16]
Running a command `gradle --quiet build` displays output like
```
$gradle --quiet build
Git dependency: Added 'testing-repo'
```
The reason is that plugin outputs all messages using `println` which is rough equivalent of `logger.quiet`, so you can't suppress them. Can you replace `println` with `logger.lifecycle` ? In this way the output of plugin can be suppressed.

**Comment by alexvasilkov** [comment]
Indeed, thanks for the feedback! I'll fix it in the next version.

**Comment by bonivi** [comment]
When the fix will be implemented ? When the next version will be released ?

**Comment by alexvasilkov** [comment]
There are no major issues fixes or features are planned yet, and this one seems quite minor for a dedicated release. Is this issue critical for you somehow?

**Comment by bonivi** [comment]
In a bash script we have something like
projectVersion=$(./gradlew -q printProjectVersion)
When we use the plugin bash variable projectVersion contains also "Git dependency..." messages

**Comment by alexvasilkov** [comment]
Aha, that must be annoying. Ok, let's see if I can release a quick fix.

**Comment by alexvasilkov** [comment]
This should be fixed now, released as 2.0.3. Feel free to reopen if you'll see any issues.
