### ISSUE TITLE
Support caching the Git repo

### ISSUE THREAD

**Issue by chris13524** [alexvasilkov/GradleVcsDependencyPlugin#19]
For each build, the Git repo is re-cloned. I suggest that in the event that the repo is already cloned, do a `git reset --hard && git pull` to save time and bandwidth.

The plugin should save the clone parameters to a file to ensure that they haven't changed (in which case a clone should be used instead).

**Comment by alexvasilkov** [comment]
Wait, why do you think that the repo is cloned on each build? It will only happen if you'll delete the directory of you git dependency. Otherwise the plugin checks if current version is changed, and then does fetch & checkout if needed.

**Comment by alexvasilkov** [comment]
Closing this one for now. Feel free to re-open if you beleive there is an issue.
