### ISSUE TITLE
Conditional dependency

### ISSUE THREAD

**Issue by Ch4t4r** [alexvasilkov/GradleVcsDependencyPlugin#2]
First off, thanks for the library. I was looking for something like this.

I was wondering whether there is a way to have conditional dependencies? My use case is that I have binaries on a private maven repo but the source code is accessible without restrictions. Based on an environment variable I then want to either use the binary or have this plugin build the dependency from the sources.
I tried something like this:

```
dependencies {
   if(!compileBinariesLocally()) {
      implementation 'group:artifact:version
   }
}

git {
    if(compileBinariesLocally()) {
        implementation "https://git.example.com/group/artifact.git", {
            name "artifact"
            projectPath "/library"
        }
    }
}

def compileBinariesLocally() {
    return project.hasProperty("compileBinaries") || getSystemVariableOrDefault("COMPILE_BINARIES", false)
}
```

which gives me `Git dependency: Config closure is invalid` when I do `./gradlew clean build -PcompileBinaries`. Without the if-branch inside the `git` block it does work.
Putting the `git` block inside of the if-branch doesn't work either.

**Comment by alexvasilkov** [comment]
Aha, interesting use case. I didn't try to use `if` block for git dependencies, but it turns out to work fine, e.g. I tried with `if (true) {...}` and `if (false) {...}` and it works as expected.

In your case I think the problem is with `getSystemVariableOrDefault()`, I cannot recognize this method, where is it from?

Also note, that even though you can access `project` field from `git {}` section it is not the same as the regular `project` instance. This is because `git {...}` block is called before the project is actually evaluated, so real `project` (`org.gradle.api.Project`) instance is simply not available at this point. Instead I'm passing `org.gradle.api.initialization.ProjectDescriptor` so that you at least have access to some basic stuff like `projectDir`.

In your case you should be able to get command line property with something like this:

```
findProperty('COMPILE_BINARIES') ?: false
```

If you need to decide on whether to include the dependency during project evaluation phase then you can play with configuration names, e.g.:

```groovy
configurations {
    conditional
    if (condition()) implementation.extendsFrom(conditional)
}
```

And the use `conditional` keyword instead of `implementation` when defining your git dependency. Note though that in this case git repo will still be cloned locally but just won't be attached as project dependency.

**Comment by Ch4t4r** [comment]
> In your case I think the problem is with getSystemVariableOrDefault(), I cannot recognize this method, where is it from?

I wrote that function myself, it tries to retrieve the value from the environment variables and returns the default specified if it can't be found. Looks like this:
```
static def getSystemVariableOrDefault(String variable, String defaultValue) {
    def value = System.getenv(variable)
    if(value == null) {
        return defaultValue
    }
    return value
}
```

> Also note, that even though you can access project field from git {} section it is not the same as the regular project instance

I've noticed that as well, which is why I added the environment variable. I didn't know the `findProperty` function.

> If you need to decide on whether to include the dependency during project evaluation phase then you can play with configuration names, e.g.: [...]

Even better. I took a look at the readme to see whether that's mentioned there, seems like I didn't see it the first time.

When I try it with 
```
def compileBinariesLocally() {
    return (findProperty("compileBinaries") != null) || System.getenv("COMPILE_BINARIES") != null
}

// I condensed the code a bit, selfCompileLibrary extends from implementation when compileBinariesLocally() returns true and vice versa
configurations {
    useCompiledBinary.extendsFrom implementation
    selfCompileLibrary
}

dependencies {
    useCompiledBinary 'group:artifact:version'
}

git {
   selfCompileLibrary "https://git.example.com/group/artifact.git"
}
```
I get unresolved references for everything this dependency includes. It seems this is unrelated to this Plugin (maybe it's something with Gradle or the Android plugin, no idea), as it even does not work when removing the git block and using simply `useCompiledBinary.extendsFrom implementation` (without any condition). I've settled on this, which does work:
```
dependencies {
 if(System.getenv("COMPILE_BINARIES") == null) {
    implementation 'group:artifact:version'
 }
}

git {
 if(System.getenv("COMPILE_BINARIES") != null) {
   implementation "https://git.example.com/group/artifact.git"
 }
}
```

Another thing that I noticed is that if I add `findProperty("compileBinaries") != null` to the condition inside the git block I get `Git dependency: 'name' is not specified`, with only `System.getenv` I don't.

**Comment by Ch4t4r** [comment]
I'm going to close this as it indeed does work out of the box. Custom configurations and `findProperty()` didn't work though.

Thanks for your help and thanks for the plugin!

**Comment by alexvasilkov** [comment]
Aha, it seems like `findProperty()` is only available for `org.gradle.api.Project` so you can't use it from `git {}` block.

Regarding configurations, your usage here is not correct actually:

```
useCompiledBinary.extendsFrom implementation
```

It should be instead:

```
useCompiledBinary
implementation.extendsFrom(useCompiledBinary)
```

**Comment by Ch4t4r** [comment]
Weird, the [Gradle docs](https://docs.gradle.org/current/userguide/declaring_dependencies.html) are wrong then:

```
configurations {
    smokeTest.extendsFrom testImplementation
}

dependencies {
    testImplementation 'junit:junit:4.12'
    smokeTest 'org.apache.httpcomponents:httpclient:4.5.5'
}
```

I initially tried it the way you wrote it as well, at that time it didn't work. Now it does, so that seems to have been something different.

**Comment by alexvasilkov** [comment]
I don't fully understand the logic behind Gradle's configurations inheritance, I just come up to this after trial and error :)
