### ISSUE TITLE
Gradle build failing when plugin included in an android library

### ISSUE THREAD

**Issue by Letal1s** [alexvasilkov/GradleVcsDependencyPlugin#23]
Hi, this is my first time messing with gradle files so I'm sorry if I've missed something obvious.

Basically, I've tried to add this plugin to my android library so that I can access a private repository as a dependency.
So far, I get the following error when attempting to build:
```
A problem occurred evaluating project ':flutter_openvpn'.
> No signature of method: build_4eoj5903tx78r66iyi9poz12f.android() is applicable for argument types: (build_4eoj5903tx78r66iyi9poz12f$_run_closure2) values: [build_4eoj5903tx78r66iyi9poz12f$_run_closure2@30e43eca]
```

I am almost certain I have followed the README word for word, so what am I doing wrong?

My settings.gradle looks like so:
```
rootProject.name = 'flutter_openvpn'
plugins {
    id 'com.alexvasilkov.git-dependencies' version '2.0.4'
}
```

And my build.gradle's android section:
```
android {
    compileSdkVersion 30

    defaultConfig {
        minSdkVersion 16

    }

    lintOptions {
        disable 'InvalidPackage'
    }

    git {
        implementation 'https://github.com/Letal1s/abcdefg.git', {
            username 'XXXXXX'
            password 'XXXXXX'
            commit 'abcd'
        }
    }
}
```

**Comment by alexvasilkov** [comment]
Try to move `git { ... }` section outside of `android`, it should be on the same level as your `dependencies { ... }` section.

**Comment by Letal1s** [comment]
I took it outside of android and I get the following: 
`> Could not find method git() for arguments [build_4eoj5903tx78r66iyi9poz12f$_run_closure3@3ca0565e] on project ':flutter_openvpn' of type org.gradle.api.Project.`
My gradle version is 6.7.1 and the only dependencies sections I had were inside 'buildscript' and 'android'. This is my full build.gradle as of now:
```
group 'com.topfreelancerdeveloper.flutter_openvpn'
version '1.0'

buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.0.2'
    }
}

rootProject.allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}

apply plugin: 'com.android.library'

android {
    compileSdkVersion 30

    defaultConfig {
        minSdkVersion 16

    }
    lintOptions {
        disable 'InvalidPackage'
    }
    dependencies {
        //implementation 'https://github.com/Letal1s/abcdefg.git'
    }
}

git {
    implementation 'https://github.com/Letal1s/abcdefg.git', {
        username 'XXXXXXX'
        password 'XXXXXXX'
        commit 'abcd'
    }
}
```

**Comment by alexvasilkov** [comment]
Do you still have 

```
plugins {
    id 'com.alexvasilkov.git-dependencies' version '2.0.4'
}
```

in your `settings.gradle`?

**Comment by Letal1s** [comment]
I do, my whole settings.gradle is the following:
```
rootProject.name = 'flutter_openvpn'
plugins {
    id 'com.alexvasilkov.git-dependencies' version '2.0.4'
}
```

Something else I have noticed is that using fetch like detailed in the README in settings.gradle works, however since it isn't added as a dependency it can't be used and I then get errors to do with classes from my repo not being available.

**Comment by Letal1s** [comment]
UPDATES:

1)
It also seems that is actually is being built with gradle 5.6.2 according to my gradle-wrapper.properties and not the gradle version I got from 'gradlew --version'. So I've updated my settings.gradle to use the other code instead of the plugins block, but I still get the same error regardless:
```
rootProject.name = 'flutter_openvpn'
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.alexvasilkov:gradle-git-dependencies:2.0.4'
    }
}

apply plugin: 'com.alexvasilkov.git-dependencies'
```

2)
As I am trying to include this in an android library's build.gradle and not an android application, I thought this would be relevant information as this might be why I am getting strange behaviour.

**Comment by Letal1s** [comment]
Sorry for the spam, but I've managed to get the repo to download into my 'libs' folder however it doesn't build correctly as the git dependency is for an android library being built not the app itself: `None of the consumable configurations have attributes.` Should I close this and open up a new issue in light of this?

**Comment by alexvasilkov** [comment]
If you have the repo downloaded then the plugin most probably works as expected and you just have a generic configuration issue, which is better to ask for on StackOverflow.

The only two thing this plugin does is downloading specified git repo and adding it as project dependency (like `implementation project(":name")`. You can start by commenting out the plugin and setup your project manually, once it builds you can switch back to the plugin.

**Comment by Letal1s** [comment]
You're right, even when trying to use the cloned repo manually and including it with `implementation project` I seem to be getting the same error. I'll close the issue now.
