### ISSUE TITLE
Can not use plugin with non-master branch

### ISSUE THREAD

**Issue by beelesnik** [alexvasilkov/GradleVcsDependencyPlugin#24]
Hello.
When I use plugin with any branch like this:
```
plugins {
    id 'com.alexvasilkov.git-dependencies' version '2.0.1'
}

git {
    fetch 'git@gitlab.com:myorg/myrepo.git', {
        dir "$rootDir/"
        branch 'mybranch'
    }
}

include 'app'
```

I got an error while executing gradle commands. 

```
Settings file '/builds/bezYZmep/0/..settings.gradle' line: 6
* What went wrong:
A problem occurred evaluating settings 'docker'.
> Ref mybranch cannot be resolved
* Try:
```

This way works well for tags. What is wrong with branches?
Maybe there is different syntax for branches or smth else?
I tried with latest version of plugin and the issue is the same for branches.
Please could You help with this issue?
Thank You

**Comment by alexvasilkov** [comment]
Indeed, please use 'origin/mybranch' for now, I'll check if I can make it implicitly.

**Comment by beelesnik** [comment]
Thanks. Will try

**Comment by beelesnik** [comment]
It works. And it is appropriate solution for me. Thank You

**Comment by caeus** [comment]
This should be added to the main docs

**Comment by alexvasilkov** [comment]
Documentation is updated now.
