### ISSUE TITLE
ERROR:org.gradle.api.internal.project.DefaultProject\_Decorated cannot be cast to org.gradle.api.initialization.Settings

### ISSUE THREAD

**Issue by odifek** [alexvasilkov/GradleVcsDependencyPlugin#3]
First, I appreciate what you have done here. I have been looking for such a solution.
But I tried to use this in my android studio project but hit an error.

 `ERROR:org.gradle.api.internal.project.DefaultProject\_Decorated cannot be cast to org.gradle.api.initialization.Settings`

I have this in my project build.gradle
```
     dependencies {
            classpath 'com.android.tools.build:gradle:3.6.3'
            classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    
            // NOTE: Do not place your application dependencies here; they belong
            // in the individual module build.gradle files
    
            classpath 'com.alexvasilkov:gradle-git-dependencies:2.0.1'
        }
```
And applied the plugin in app build.gradle
```
    apply plugin: 'com.android.application'
    apply plugin: 'kotlin-android'
    apply plugin: 'kotlin-android-extensions'
    
    apply plugin: 'com.alexvasilkov.git-dependencies'
```

**Comment by Ch4t4r** [comment]
I believe you have to put it into settings.gradle, not build.gradle.

For me it works, my settings.gradle looks like this:
```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.alexvasilkov:gradle-git-dependencies:2.0.1'
    }
}
apply plugin: 'com.alexvasilkov.git-dependencies'

include ':library'
```

**Comment by alexvasilkov** [comment]
@Ch4t4r Is right, the pugin should be defined in `settings.gradle`, not in `build.gradle`. Settings and projects plugins are quite different so you cannot define settings plugin in your project build script. Please follow the docs in readme :)

**Comment by odifek** [comment]
Great. Thanks @Ch4t4r and @alexvasilkov
