### ISSUE TITLE
Gradle properties in build.gradle git block

### ISSUE THREAD

**Issue by bclayton-usgs** [alexvasilkov/GradleVcsDependencyPlugin#5]
Is there a way to use properties defined in the gradle.properties file inside the git block in the build.gradle file?

I would like to define the tag to use in the gradle.properties file and then reference that in the git block of the build.gradle file. 

Right now I get a `No such property: <property> for class: build` were `property` is a property in the gradle.properties file.

**Comment by alexvasilkov** [comment]
You cannot access project's properties from `git {}` block since this block is evaluated before the project (`org.gradle.api.Project`) is actually created. To access `gradle.properties` from `git {}` block you will have to read it manually like this:

```
def props = new Properties()
new File("${project.parent.projectDir}/gradle.properties").withInputStream { props.load(it) }
println props.getProperty('{name of your property}')
```

That's quite cumbersome unfortunatelly.

**Comment by bclayton-usgs** [comment]
Thanks for the information.
