### ISSUE TITLE
Incompatible with gradle version 6.5

### ISSUE THREAD

**Issue by jeffreydelooff** [alexvasilkov/GradleVcsDependencyPlugin#6]
Results in a
```
Caused by: java.lang.ClassCastException: org.gradle.api.internal.project.DefaultProject_Decorated incompatible with org.gradle.api.initialization.Settings
	at com.alexvasilkov.gradle.git.SettingsPlugin.apply(SettingsPlugin.groovy)
```

**Comment by alexvasilkov** [comment]
Version 2.0.1 works fine for me with Gradle 6.5 in several different projects. Please provide more details about your usage otherwise I can do little.

Stacktrace you shared saying that sombody is trying to cast `Project` instance to `Settings` which makes little sense to me.

**Comment by bmc08gt** [comment]
@jeffreydelooff are you trying to apply the plugin in the root build.gradle? it needs to be applied in `settings.gradle`

**Comment by jeffreydelooff** [comment]
Ahh that might have been it. It wasn't in `settings.gradle`. My bad.
