### ISSUE TITLE
[Question] How to use pre-fetch build scripts?

### ISSUE THREAD

**Issue by fjr619** [alexvasilkov/GradleVcsDependencyPlugin#9]
1. You can also specify git repos in settings.gradle similar as it is done in build.gradle but use fetch instead of configuration name:
```
git {
    fetch 'https://example.com/repository.git', {
        dir "$rootDir/gradle/scripts"
        tag 'v1.2.3'
    }
}
```
with that my repo will clone into `/gradle/scripts`, how to use it?

2. if i make code changes in that clone repo how to commit? do i need to create new branch? because it refer to tag `1.2.3` if i make a new commit will it update di references in the host project like `git sub-modules`?

**Comment by alexvasilkov** [comment]
1. You can import other scripts with "apply from" syntax, see [Gradle docs](https://docs.gradle.org/current/userguide/plugins.html#sec:script_plugins).

`apply from: "$rootDir/gradle/scripts/{script_file}"`

2. You should work with it as with a standalone git repo, it is not related to the host proejct's repo in any way.
Once you'll commit you changes don't forget to update your scripts version to the new reference (commit hash or tag name).
